watcher:
  watch_patterns:
  - '**/*.py'
  - '**/*.md'
  - '**/*.yaml'
  ignore_patterns:
  - __pycache__
  - .git
  - .pytest_cache
  - venv
  - env
  - build
  - dist
  - '*.egg-info'
  - htmlcov
  debounce_seconds: 2.0
  max_concurrent_updates: 3
updater:
  auto_update:
    tests: false
    docs: false
    dependent_code: false
  update_modes:
    tests: suggest
    docs: suggest
    code: manual
  validation:
    run_tests: true
    check_coverage: true
    lint_code: true
claude_integration:
  enabled: true
  model: claude-3-opus-20240229
  max_tokens: 4096
  instructions:
    test_creation: Create comprehensive unit tests following existing patterns
    test_update: Update tests to cover changes, maintain existing test style
    doc_update: Update documentation to reflect changes, keep examples current
  # Environment variable overrides
  env_overrides:
    model: CLAUDE_MODEL
    max_tokens: CLAUDE_MAX_TOKENS
    enabled: CLAUDE_INTEGRATION_ENABLED
rules:
  test_file_pattern: tests/unit/test_{module}.py
  doc_file_pattern: docs_src/api/{module}.md
  coverage_threshold: 0.95
  require_tests_for_new_code: true
