global:
  alert_channels: []
  backup_retention_days: 7
  enable_audit_logging: true
  enable_cloud_backup: false
  enable_cross_project_insights: true
  enable_knowledge_sharing: true
  enable_pattern_learning: true
  enable_project_isolation: true
  global_cpu_cores: 2
  global_discord_guild: null
  global_disk_limit_gb: 10
  global_memory_limit_gb: 4
  global_state_path: .orch-global
  health_check_interval_seconds: 120
  max_concurrent_projects: 5
  max_total_agents: 10
  monitoring_webhook_url: null
  resource_allocation_strategy: fair_share
  resource_rebalance_interval_seconds: 600
  scheduling_interval_seconds: 60
  secret_management_provider: local
projects: {}
