global:
  max_total_agents: 12
  max_concurrent_projects: 5
  global_memory_limit_gb: 8
  resource_allocation_strategy: "priority_based"
  scheduling_interval_seconds: 30
  resource_rebalance_interval_seconds: 300
  health_check_interval_seconds: 60
  global_state_path: ".orch-global-state"
  global_discord_guild: null

projects:
  - name: "test-project"
    path: "."
    orchestration: "blocking"
    priority: "normal"
    resources:
      max_parallel_agents: 3
      max_memory_mb: 2048
      cpu_priority: 1.0