global:
  alert_channels: []
  backup_retention_days: 30
  enable_audit_logging: true
  enable_cloud_backup: false
  enable_cross_project_insights: true
  enable_knowledge_sharing: true
  enable_pattern_learning: true
  enable_project_isolation: true
  global_cpu_cores: 4
  global_discord_guild: null
  global_disk_limit_gb: 50
  global_memory_limit_gb: 8
  global_state_path: .orch-global
  health_check_interval_seconds: 60
  max_concurrent_projects: 10
  max_total_agents: 20
  monitoring_webhook_url: null
  resource_allocation_strategy: fair_share
  resource_rebalance_interval_seconds: 300
  scheduling_interval_seconds: 30
  secret_management_provider: local
projects: {}
