name: Dependency Check

on:
  pull_request:
    paths:
      - '**.py'
      - '**.md'
      - 'dependencies.yaml'
  push:
    branches: [main, develop]

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml watchdog
    
    - name: Validate dependencies
      run: |
        python tools/dependencies/tracker.py --validate
    
    - name: Check for missing tests
      run: |
        python tools/dependencies/tracker.py --check-missing-tests
    
    - name: Generate dependency report
      if: always()
      run: |
        python tools/dependencies/tracker.py --export-graph
        
    - name: Upload dependency graph
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: dependency-graph
        path: dependency_graph.json
